# Generated by Django 4.0.4 on 2022-06-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='problem',
            field=models.CharField(max_length=20),
        ),
    ]
