# Generated by Django 4.0.3 on 2022-04-22 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emailId',
        ),
    ]
