# Generated by Django 4.0.4 on 2022-06-28 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0001_initial'),
        ('users', '0006_alter_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='diet.diet'),
        ),
    ]
