# Generated by Django 4.0.4 on 2022-07-01 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_exercise_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exercise_frequency',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
