# Generated by Django 4.0.4 on 2023-04-12 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_exercise_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
