# Generated by Django 4.0.4 on 2023-04-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_profile_f_name_remove_profile_l_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
